
//ReferenceError






try {
    let result ; 
    result = 5 + 2 ;
    console.log(sum);
} 
catch (e) {
    console.log(e.message);
}


let num ;
num = 5 ; 
console.log(num);

